// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdMmXyX_tit9vRNbKCfDZ5M3tFtixKFRw',
    appId: '1:860161283506:ios:c366bfaff0bc3fe32b40ab',
    messagingSenderId: '860161283506',
    projectId: 'improveconnectapp',
    databaseURL: 'https://improveconnectapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'improveconnectapp.firebasestorage.app',
    iosBundleId: 'com.example.improveConnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiLhpRtoPcCC-vem3vKNsGOBM_5EbH9XQ',
    appId: '1:860161283506:web:a54e779247cdd5b82b40ab',
    messagingSenderId: '860161283506',
    projectId: 'improveconnectapp',
    authDomain: 'improveconnectapp.firebaseapp.com',
    databaseURL: 'https://improveconnectapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'improveconnectapp.firebasestorage.app',
    measurementId: 'G-FY8Z6798MK',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiLhpRtoPcCC-vem3vKNsGOBM_5EbH9XQ',
    appId: '1:860161283506:web:f701ea1e10574a072b40ab',
    messagingSenderId: '860161283506',
    projectId: 'improveconnectapp',
    authDomain: 'improveconnectapp.firebaseapp.com',
    databaseURL: 'https://improveconnectapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'improveconnectapp.firebasestorage.app',
    measurementId: 'G-6K57QY166V',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdMmXyX_tit9vRNbKCfDZ5M3tFtixKFRw',
    appId: '1:860161283506:ios:c366bfaff0bc3fe32b40ab',
    messagingSenderId: '860161283506',
    projectId: 'improveconnectapp',
    databaseURL: 'https://improveconnectapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'improveconnectapp.firebasestorage.app',
    iosBundleId: 'com.example.improveConnectApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuobANmS-FjCP0ampC0cx1rKl0Srh-xSg',
    appId: '1:860161283506:android:70bc308df265349b2b40ab',
    messagingSenderId: '860161283506',
    projectId: 'improveconnectapp',
    databaseURL: 'https://improveconnectapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'improveconnectapp.firebasestorage.app',
  );

}